andela/travel_tool_front

README.md
dev.dockerfile
docker.sh

- It creates a docker file that will create an image for development purposes.
- It creates a script file that will make easier for developers to run docker commands.
- Create a docker container for development that will allow hot-reloading and live editing.
- By running the following commands
`./docker.sh development` (for development purposes)
`./docker.sh production` (for production purposes)
Before running the docker commands, make sure you have all the npm packages installed required for the application. Additionally, for production testing, make sure you first build the application by running:
`npm run build`
#159325778

#159325778 create a docker container for development

---

src/components/Forms/NewChecklistForm/index.jsx
src/redux/actionCreator/__tests__/travelChecklistActions.test.js
src/redux/middleware/__tests__/travelChecklistSaga.test.js
src/redux/middleware/index.js
src/redux/middleware/travelChecklistSaga.js
src/redux/reducers/__tests__/travelChecklist.test.js
src/redux/reducers/travelChecklist.js
src/views/Checklist/index.js

ft(tests): Add saga tests

---

src/components/Forms/FormsAPI/Input/InputFields/__tests__/CheckBox.test.js
src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
src/components/Forms/NewChecklistForm/__tests__/index.js
src/components/Forms/NewChecklistForm/index.jsx
src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
src/components/Forms/NewUserRoleForm/__test__/__snapshots__/NewUserRoleForm.test.js.snap
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/redux/middleware/travelChecklistSaga.js
src/redux/middleware/userDataSaga.js
src/redux/reducers/travelChecklist.js
src/services/__tests__/NotificationsAPI.test.js
src/services/__tests__/UserAPI.test.js
src/services/__tests__/apiErrorHandler.test.js
src/services/__tests__/travelChecklistAPI.test.js
src/services/apiErrorHandler.js
src/views/Checklist/__tests__/index.js
src/views/Checklist/index.js

Integrate admin related features

---

src/components/LeftSideBar/Metadata/index.js
src/routes/index.js
src/services/__tests__/travelChecklistAPI.test.js
src/services/travelChecklistAPI.js

Ft create travel checklist 161044514

---

src/components/Forms/NewChecklistForm/FormFieldSets/index.jsx

Fix the front-end deployment issue 
Add missing semi-colon in checklistFieldSet component
N/A
N/A
[161341165](https://www.pivotaltracker.com/story/show/161341165)
N/A
N/A

Fix deployment error from linting

---

src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/components/TravelCalendar/TravelCalendar.scss
src/components/TravelCalendar/index.jsx
src/components/TravelCalendarDetails/__tests__/TravelCalendarDetails.test.js
src/components/TravelCalendarDetails/__tests__/__snapshots__/TravelCalendarDetails.test.js.snap
src/components/TravelCalendarDetails/index.jsx
src/redux/reducers/travelCalendar.js
src/services/TravelCalendarAPI.js
src/services/__tests__/TravelCalendarAPI.test.js
src/views/Documents/__tests__/__snapshots__/DeleteModal.test.js.snap
src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap

Connect the travel calendar API service to the make calls to the travel calendar API implemented in the backend.
- Make travel calendar API send requests to the travel calendar backend implementation
- Make travel calendar details show by default
You should have your back-end server running
After Logging in, change your user role to  travel administrator in the database
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_back.git```
- Change directory to the repo in your text editor-```cd travela_tool_back```
- Open the project in your text editor
- Run ```git fetch``` on your terminal
- Checkout to this branch-```git checkout ft-see-travel-calender-161374998```
- Run ```yarn install``` on your terminal
- Run ```yarn start:dev``` on your terminal to …

#161374570 Connect to travel calendar API

---

src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/LeftSideBar/Metadata/index.js
src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
src/components/RequestsModal/ConfirmDialog/ConfirmDialog.jsx
src/components/RequestsModal/ConfirmDialog/ConfirmDialog.scss
src/components/RequestsModal/RequestModalHelper.js
src/components/RequestsModal/RequestsModal.jsx
src/components/RequestsModal/__tests__/RequestsModal.test.js
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Table/Table.scss
src/components/Table/index.jsx
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/components/VerificationsPanelHeader/__tests__/ApprovalsPanelHeader.test.js
src/components/VerificationsPanelHeader/__tests__/__snapshots__/ApprovalsPanelHeader.test.js.snap
src/components/VerificationsPanelHeader/index.jsx
src/components/button-group/ButtonGroup.jsx
src/redux/middleware/index.js
src/redux/reducers/approvals.js
src/routes/index.js
src/services/__tests__/ApprovalAPI.test.js
src/services/approvalsAPI.js
src/views/Verifications/__tests__/Verifications.test.js
src/views/Verifications/index.jsx

Provides user interface for travel team members to view approved requests and verify them
- travel team members can view list of verified and approved requests for their centers
- travel team members can see a modal with a button to click to verify a request
- requester gets an in-app notification stating the request has been verified
- Enter into the project directory - `cd travel_tool_front`
- checkout the branch `git checkout ft-verify-request-162045684`
- Start the server with `make start`
- Clone the backend repo `git clone https://github.com/andela/travel_tool_back.git`
- checkout the branch `git checkout ft-verify-request-162045684`
- Start the server with `make start`
- Visit …

#162045684 Enable travel team members verify requests

---

src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
src/components/CheckBox/Checkbox.scss
src/components/CheckBox/__tests__/__snapshots__/Checkbox.test.js.snap
src/components/CheckBox/index.jsx
src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
src/components/Forms/FormsAPI/Input/_input.scss
src/components/Forms/NewRequestForm/FormFieldsets/PersonalDetails.jsx
src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/Forms/NewRequestForm/NewRequestForm.jsx
src/components/Forms/NewRequestForm/NewRequestForm.scss
src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap

- Fix checkbox and multi-trip cancel icon designs in request modal
- Fix checkbox request modal to match mockup
- Fix cancel icon in multi-trip request to match mockup
- Clone the repo - git clone https://github.com/andela/travel_tool_front.git
- Change into the project directory
- Run ```git checkout bg-fix-request-modal-design-161962033```
- Then Run ```yarn start```
- Click ```New request``` to popup new request modal
- Check the alignment of the send request and compare to the mocks 
- Check the cancel icon in multi-trip and compare it to the mocks
- Check alignment of personal details and remember my personal details and compare to the mockup
- Check on space between remember my personal details and travel details and compare to mockups
[Request Form …

 #161962033 Fix request modal fields to match designs

---

src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/Forms/ProfileForm/ProfileForm.scss
src/components/Table/__tests__/Table.test.js
src/components/Table/index.jsx
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/components/button-group/ButtonGroup.jsx

Fix notification badge on verification page.
* Change counts badge on ``` pending verifications ``` button to white when active, just like it is for other buttons in other pages.
* Change request badge for open requests to 'Manager stage', and for approved requests to 'Travel stage'.
* Reduce margin between the buttons on the verifications page.
* Clone the repo with ``` git clone https://github.com/andela/travel_tool_back.git ```
* cd to travel_tool_front
* Checkout to the branch ``` bg-fix-notification-badge-on-verification-page-162237283 ```
* Run `` yarn ``` to install dependencies
* Start up the server with ``` yarn start ```
* Visit https://travela-local.andela.com
* Login to the application
* Make two travel requests. one should be approved, while the other open.
* Navigate to ``` …

#162237283 Fix notification badge on verification page.

---

src/components/Forms/AddRoleForm/__tests__/__snapshots__/AddRoleForm.test.js.snap
src/components/Forms/FormsAPI/Input/InputFields/__tests__/__snapshots__/filterDropdownSelect.test.jsx.snap
src/components/Forms/FormsAPI/Input/InputFields/__tests__/filterDropdownSelect.test.jsx
src/components/Forms/FormsAPI/Input/InputFields/filterDropdownSelect.jsx
src/components/Forms/FormsAPI/Input/_input.scss
src/components/Forms/FormsAPI/Input/index.jsx
src/components/Forms/FormsAPI/formEventHandlers/eventHandlerCreators.js
src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
src/components/Forms/NewChecklistForm/__tests__/index.js
src/components/Forms/NewDocumentForm/__tests__/__snapshots__/NewDocumentForm.test.js.snap
src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/Forms/NewRequestForm/NewRequestForm.jsx
src/components/Forms/NewUserRoleForm/__tests__/__snapshots__/NewUserRoleForm.test.js.snap
src/components/Forms/ProfileForm/FormFieldsets/ProfileDetails.jsx
src/components/Forms/ProfileForm/ProfileForm.scss
src/components/Forms/ProfileForm/_tests_/__snapshots__/ProfileForm.test.jsx.snap
src/components/Forms/ProfileForm/index.jsx
src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap

* Validate roles field in profile and request page.
* Role field should display an error when the field is cleared.
* Clone this repo: `https://github.com/andela/travel_tool_front.git`.
* Checkout to: `bg-validate-role-field-#162156678`.
* Install dependencies: `yarn install`.
* Run app: `yarn start`.
Test roles field in new requets modal
* Click on `My Request`.
* Click on `New Request`.
* Clear `Your Roles` fileds.  
Test roles field in profile page
* Click on `Profile`.
* In personal details form clear `name` field.
[162156678](https://www.pivotaltracker.com/story/show/162156678)

#162156678 Fix(validate role field): Role field should display an error when empty

---

src/components/Pagination/AnalyticsPagination.jsx
src/components/Pagination/__tests__/AnalyticsPagination.test.js
src/components/Pagination/__tests__/__snapshots__/AnalyticsPagination.test.js.snap
src/components/Pagination/_analyticsPagination.scss
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/TravelCalendar/__tests__/TravelCalendar.test.js
src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
src/components/TravelCalendar/index.jsx
src/components/TravelCalendarDetails/index.jsx
src/services/TravelCalendarAPI.js
src/services/__tests__/TravelCalendarAPI.test.js

Adds pagination to the Travel calendar section of the dashboard
1. Create a pagination component for Analytics page
2. Update data in the travel calendar based on the page user is in
3. Write tests for the pagination component
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_back.git```
- Change directory to the repo in your text editor-```cd travela_tool_back```
- Open the project in your text editor
- Run ```yarn install``` on your terminal
- Run ```yarn start:dev``` on your terminal to start the backend server
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_front.git``` 
- Change directory to the repo in your text editor-```cd travela_tool_front```
- Open the project in your text editor
- Run ```git …
```

#162173129 Add pagination to the travel calendar 

---

src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
src/components/Forms/FormsAPI/formValidator/index.js
src/components/Forms/NewAccommodationForm/__tests__/NewAccommodation.tests.js
src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/Forms/NewRequestForm/NewRequestForm.jsx
src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap

Adds a validator to issue warning if user has input same location for origin and destination of travel.
Currently the user can submit same location for destination and origin.This PR adds changes to the validator to make sure this ain't so.When a user submits their locations, they're compared and if they happen to be same a warning is issued.
-  Change into the project directory -`cd travel_tool_front`
-  Pull and checkout into this branch - `ch-same-origin-destination-validation-#162181277`
-  Install project dependencies using yarn install
- Sign in and open the new requests page.
- In the travel details section, input the same location for origin and destination of travel.You should see a warning pop up on …

#162181277 add validation to check destination and origin and issue warning if same.

---

src/components/Forms/NewRequestForm/NewRequestForm.jsx

- Remove console.log from the new request component 
- Remove console.log from the new request component
- console.log are not allowed in staging and production environment  
[161877486](url)
- None
- None

#161877486 Remove console.log from component

---

src/components/Forms/ChangeBedForm/index.jsx
src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
src/components/RequestsModal/TripDetails/index.jsx

Add hotel booking to the available rooms drop down
- Add `Hotel Booking` to the options on the New request Form for `Available Rooms`
- remove the `No rooms Found Option`
- display `Hotel Booking` when viewing the details of the trip across the application.
- Enable `Travel Team` members re-assign rooms to travel requesters `Hotel Booking`.
- checkout this branch - `git checkout ch-update-accomodation-162382135`
- run `yarn db:rollmigrate` on the backend directory and run `yarn start:dev`
- checkout this branch - `git checkout ch-add-hotel-booking-162382135`
- login to the app
- set your user role to 'Travel …

#162382135 Add hotel booking option

---

cypress/support/commands.js

-  Setup file upload for end-to-end test
- A function that allows files to be uploaded during end to end testing
- None
- The function can be used by calling it example `cy.uploadFile('/image/house.png', 'image/png')` 
- [162584782](https://www.pivotaltracker.com/story/show/162584782)
- None
- None

#162584782 Setup file upload for end to end test 

---

src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/helper/accommodationReducer.js
src/redux/actionCreator/accommodationActions.js
src/redux/middleware/__tests__/accommodationSaga.test.js
src/redux/middleware/accommodationSaga.js
src/redux/reducers/__tests__/accommodation.test.js
src/redux/reducers/accommodation.js
src/views/Accommodation/Accommodation.scss
src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/EditGuestHouseDetails.test.js.snap
src/views/Accommodation/FullGuestHouseDetails/__tests__/__snapshots__/FullGuestHouseDetails.test.jsx.snap
src/views/Accommodation/FullGuestHouseDetails/index.jsx
src/views/Accommodation/__tests__/__snapshots__/Accommodation.test.js.snap
src/views/Accommodation/index.jsx

This PR fixes the guesthouse bugs
* Reset save button to default state after create guesthouse request has been made.
* Move the disable guesthouse redirection to the saga.
* Add a loading animation and disable the `disable guesthouse` button when it's clicked on.
- Check in to the project directory
- Checkout the **bg-fix-disable-guesthouse-inconsistency-162541358** branch
`git checkout bg-fix-disable-guesthouse-inconsistency-162541358`
- Install dependencies and start the server as stated in the ReadMe on this repository.
- Start the [backend](https://github.com/andela/travel_tool_back) of …

#162541358 Fix bugs with creating and disabling guesthouses

---

src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
src/components/Forms/NewRequestForm/NewRequestForm.jsx
src/services/AvailableRoomsAPI.js

- Add accommodation option to one-way trips.
- Right now, a user booking a one-way trip is not able to select an accommodation option.
This PR adds functionality to enable a user booking a one-way trip to be able to select an 
accommodation option so they are not stranded in their new location.
- Checkout the **ft-one-way-trip-accommodation-162573849** branch
`git checkout ft-one-way-trip-accommodation-162573849`
- Start the [backend](https://github.com/andela/travel_tool_back/pull/213) of this project. (Instructions …

#162573849 Add accommodation option

---

src/components/AnalyticsReport/__tests__/AnalyticsReport.test.js
src/components/AnalyticsReport/index.jsx
src/components/PieChartAnalytics/__tests__/PieChartAnalytics.test.js
src/components/PieChartAnalytics/index.jsx
src/components/StatsAnalytics/__tests__/StatsAnalytics.test.js
src/components/StatsAnalytics/__tests__/__snapshots__/StatsAnalytics.test.js.snap
src/components/StatsAnalytics/index.jsx
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/components/TravelCalendar/__tests__/TravelCalendar.test.js
src/components/TravelCalendar/index.jsx
src/components/TravelReadiness/__tests__/travelReadiness.test.js
src/components/TravelReadiness/index.jsx
src/redux/reducers/__tests__/readiness.test.js
src/redux/reducers/readiness.js
src/views/Analytics/index.jsx
src/views/Dashboard/index.scss

Display error messages to a user viewing dashboard page
- get a server error response
- display error response on each dashboard component accordingly
- Checkout the **bug-dashboard-error-messages-162373925** branch
`git checkout bug-dashboard-error-messages-162373925`
- Login as admin
- Navigate to [travela …

#162373925 Fix dashboard page to show correct error message to user

---

src/components/Timeline/Timeline.scss
src/views/Role/Role.scss
src/views/Role/index.jsx
src/views/RoleDetails/RoleDetails.scss
src/views/RoleDetails/index.js

Places the change center modal at the center of the page.
-  ensure the change center modal is at the center of the page
- ensure the user role modal is at the center of the page
- Checkout the **ch-change-center-modal-162640479** branch
`git checkout ch-change-center-modal-162640479`
- Login as admin
- Navigate to …

#162640479 Fix position of the Add User Role Modal

---

src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
src/components/Forms/NewRequestForm/NewRequestForm.jsx
src/components/Forms/NewRequestForm/__tests__/NewRequestForm.test.jsx
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/views/Accommodation/__tests__/Accommodation.test.js
src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
src/views/Requests/__tests__/Requests.test.js

Fixes the cancel modal button issues.
- Terminate the create request modal when the cancel button is clicked
- Terminate the edit request modal when the cancel button is clicked
- Terminate the create guest house modal when the cancel button is clicked
- Checkout the **bg-fix-cancel-modal-button-issues-162755938** branch
`git checkout bg-fix-cancel-modal-button-issues-162755938`
- Navigate to …

#162755938 Fix the modal cancel button issues

---

src/components/Forms/NewAccommodationForm/NewAccommodation.jsx
src/components/RequestsModal/RequestsModal.jsx
src/components/Table/index.jsx
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/redux/middleware/accommodationSaga.js
src/redux/reducers/accommodation.js
src/views/Accommodation/FullGuestHouseDetails/index.jsx
src/views/Approvals/index.jsx
src/views/ErrorPages/NotFound/NotFound.scss
src/views/ErrorPages/NotFound/index.jsx
src/views/Requests/__tests__/Requests.test.js
src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
src/views/Requests/index.jsx
src/views/Verifications/index.jsx

- disable the error page from rendering in the background
The error page should only pop out when data has been fetched from the backend.
- Setting up the backend
- Clone the repo - `git clone https://github.com/andela/travel_tool_back.git`
- Enter into the project directory - `cd travel_tool_back`
- checkout the branch git checkout `develop`
- Install dependencies using `yarn install`
- Rollback and run database migrations with `yarn db:rollmigrate`
- start the backend server with `yarn run start:dev or make start`
- Setting up the frontend
- Enter into the project directory - `cd travel_tool_front`
- Checkout to the branch `fix-error-page-prompts-162756406` then run the app `yarn start` or `make start`
- …

#162756406 Fix prompting 404 page when fetching requests by id

---

src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap

This PR makes sure default accommodation options are available.
* Make `Not Required` and `Hotel Booking` accommodation option available as defaults.
- Clone the front end repository with ```git clone https://github.com/andela/travel_tool_front ``` 
- CD into ```travel_tool_front ``` 
- Checkout the **bg-accommodation-availability-multicity-162711180** branch
`git checkout bg-accommodation-availability-multicity-162711180`
- Install dependencies and start the server as stated in the ReadMe on this repository.
- Navigate to [travela](http://travela-local.andela.com:3000/) in your browser and log in with your …

#162711180 Display default options for accommodation

---

src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
src/views/Accommodation/FullGuestHouseDetails/__tests__/FullGuestHouseDetails.test.jsx
src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
src/views/Dashboard/DashboardContext/__tests__/__snapshots__/FilterContext.test.js.snap

Merge the `Release pilot` to `develop`

Merge the release pilot to develop
