andela/travel_tool_front

- src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
- src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
- src/components/modal/Modal.jsx
Fixes the bug of clicking several times to go back to the accommodation details page after clicking close modal icon without making any changes.
Ensure back arrow in a guest house details is clicked once to go back to accommodation details.
- Clone the repo `https://github.com/andela/travel_tool_front.git`
- Checkout to the branch:
```bg-backward-arrow-guesthouse-details-161176677```
- Install dependancies:
```yarn install```
- Start the application:
```yarn start```
- Log in locally and navigate to manage page in `Residence menu`
- Click to a guest room and click `edit guest room`
- Close the modal without making any changes
- Click the back arrow `<-` button once
You should have the user role of a Travel Administrator or Super Administrator to be able to see the `manage` page. To do …
> #161176677 Fix Back Arrow Redirect to GuestHouse Details 

- src/components/Forms/FormsAPI/index.js
- src/components/Forms/FormsMetadata/NewRequestFormMetadata/inputLabels.js
- src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
- src/components/Forms/NewRequestForm/NewRequestForm.jsx
- src/components/RequestsModal/TripDetails/index.jsx
- src/components/TravelCheckList/travelSubmission.scss
This PR updates Return Date field on a multi-city trip request form
- change the label from 'Return' to 'Leaving'
- autofill next trip departure date with the return date of preceding trip
- Change into the project directory -` cd travel_tool_front`
- Pull and checkout into this branch - `ch-remove-multi-trips-return-date-161981260`
- Install project dependencies using `yarn install`
- Clone the [Travela backend](https://github.com/andela/travel_tool_back)
- Run database migrations using `yarn run db:rollmigrate`
- Check `.env.example` and set up your `.env` appropriately
- Start the Server and Frontend with `make start` and log into the application
- Create a new travel request
- On the new request form, for a …
> #161981260 Change multi-trip return date

- src/components/Forms/NewDocumentForm/NewDocumentForm.scss
- src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetailsItem.test.js.snap
- src/components/Forms/NewRequestForm/NewRequestForm.jsx
- src/components/Forms/NewRequestForm/NewRequestForm.scss
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/views/Analytics/__tests__/__snapshots__/Analytics.test.js.snap
- Disable the available rooms dropdown on the accommodation page by default.
- Enable available rooms dropdown once the gender, travel-to, departure and arrival date have been filled
- Clear available rooms dropdown once a user has changed their gender, travel-to, departure and arrival date
- The grey area on a one-way trip extends the form when the user selects One Way Trip
- The dropdown should only be selectable when every other required field have been filled i.e it should be disabled
- A value of 5( digits) should not be displayed in the select box where there are no rooms available
- The grey area on a one-way trip should extend the form when the user selects One Way Trip
- The UI design on submission areas should line up with what is on …
> #161888236 Accommodation selection field on request initiation form

- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/views/Analytics/__tests__/Analytics.test.js
- src/views/Analytics/__tests__/__snapshots__/Analytics.test.js.snap
- src/views/Analytics/index.jsx
View a clickable card for 'Total number of pending requests'
- Link pending requests card to my verifications 
- Clone the repo `https://github.com/andela/travel_tool_front.git`
- Checkout to the branch:
`ft-pending-requests-analytics-162046605`
- Install dependencies:
```yarn install```
`yarn test`
- All the tests should be passing
- Start the application:
```yarn start```
- Login to the application
- Navigate to the dashboard page on the sidebar
- The pending requests card should be clickable and takes you to `/requests/my-verifications` page
2. You should have the user role of a Travel Administrator or Super Administrator to be able to see the `manage` page. To do that:
- Download `Postico` and connect to your travela database with relevant details: Db name, password, port, user
- …
> #162046605 Link pending requests card to my verifications page

- src/components/Forms/NewDocumentForm/__tests__/NewDocumentForm.test.js
- src/components/Forms/NewDocumentForm/index.jsx
Show a validation message for files with filenames starting with digits and disable 'save' button.
- prevent filename from starting with digits
- show error message on the input field
- checkout this branch - `git checkout bg-fix-document-filename-162154742`
- run `yarn db:rollmigrate` on the backend directory and run `yarn start:dev`
- go to `http://localhost:3000/documents`
- add a new document and set the name beginning with a digit
None
[#162154742](https://www.pivotaltracker.com/story/show/162154742)
None
> #162154742 Fix Upload errors for files with filenames starting with digits

- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
- src/components/Table/Table.scss
- src/components/Table/index.jsx
- src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
- src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
- src/components/TravelCheckList/SubmissionsUtils.jsx
- src/hoc/authHoc.js
- src/views/Requests/__tests__/Requests.test.js
- src/views/Requests/index.jsx
This PR ensures that the token is reset to the header when the checklist submission modal is closed.
- Remove token from header while uploading file to cloudinary
- Add token back to header when file upload is done or modal is closed.
- Enter into the project directory - `cd travel_tool_front`
- switch to this branch - `bg-fix-checklist-submissions-162008362`
- Install dependencies and start the  app - `make start`
-  [Start](https://github.com/andela/travel_tool_back/pull/174)  the backend.
- Navigate to [travela](http://travela-local.andela.com:3000) in your browser and login
- Go to the `DB` and on the `UserRoles` table, set yourself as a `Manager`
- Go to the browser, refresh the page,
- Make a `New …
> #162192282 Fix checklist submissions issues

- src/components/Forms/NewAccommodationForm/FormFieldsets/AccommodationDetails.jsx
- src/components/Forms/ProfileForm/ProfileForm.scss
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/TripDetails.scss
Fixes the spacing above the dropdown so that it matches the mockup.
There is some spacing in the drop down not needed in the application. It is expected that the unnecessary spacing does not exist on drop-down options in forms.
- Clone the repo - git clone https://github.com/andela/travel_tool_front.git
- Change into the project directory
- Run ```git checkout bg-fix-dropdown-input-162181076```
- Then Run ```yarn start```
- Ensure you set your role to `Travel Admin`
- Navigate to `Residence` and click `Manage`. Click `Add Guesthouse`
- Click `RoomType` dropdown
[162181076 ](https://www.pivotaltracker.com/story/show/162181076)
> #162181076 Fix spacing of dropdown input

- src/components/Forms/NewRequestForm/FormFieldsets/TravelDetails.jsx
- src/components/Forms/NewRequestForm/NewRequestForm.jsx
- src/components/Forms/NewRequestForm/NewRequestForm.scss
This PR enables the origin field in a multicity trip request to be prefilled with the destination of the preceeding trip
- autofill origin field with the destination of preceding trip in a multicity trip request.
- Change into the project directory -` cd travel_tool_front`
- Pull and checkout into this branch - `ch-autofill-multicity-origin-date-162045984`
- Install project dependencies using `yarn install`
- Clone the [Travela backend](https://github.com/andela/travel_tool_back)
- Run database migrations using `yarn run db:rollmigrate`
- Check `.env.example` and set up your `.env` appropriately
- Start the Server and Frontend with `make start` and log into the application
- Create a new travel request
- On the …
> #162192899  Auto-fill multicity request origin field 

- src/components/AnalyticsReport/index.jsx
- src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
- src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
- src/components/Forms/NewAccommodationForm/__tests__/__snapshots__/NewAccommodation.tests.js.snap
- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
- src/components/RequestsModal/CommentBox/__tests__/__snapshots__/RequestApproval.test.js.snap
- src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
- src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
- src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
- src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
- src/components/TravelReadiness/TravelReadiness.scss
- src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
- src/components/TravelReadiness/__tests__/travelReadiness.test.js
- src/components/TravelReadiness/index.jsx
- src/redux/middleware/travelReadinessSaga.js
- src/services/ReadinessAPI.js
- src/services/__tests__/ReadinessAPI.test.js
- src/views/Requests/__tests__/__snapshots__/Requests.test.js.snap
-Enable Travel admin should view travel readiness of potential travelers to their center and out of their centers
- Admin is able to toggle between travel readiness of inflow and outflow
- Admin is able to download the CSV for inflow and outflow data
- Change directory - `cd travel_tool_front`
- Checkout to current branch - `git checkout ft-toggle-travel-readiness-card-162046982`
- Run application - `yarn start`
- Login into the application
- Start the backend of the application on [this PR](https://github.com/andela/travel_tool_back/pull/177)
- Assign yourself the role of admin in the database
- Refresh the frontend
- Click on dashboard 
- Check travel readiness and perform inflow and outflow including …
> #162046982 Toggle travel readiness for outflow and inflow

- src/components/AnalyticsReport/__tests__/__snapshots__/AnalyticsReport.test.js.snap
- src/components/LeftSideBar/Metadata/index.js
- src/components/LeftSideBar/__tests__/__snapshots__/LeftSideBar.test.js.snap
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
- src/components/TravelReadiness/index.jsx
- src/views/Dashboard/index.jsx
Allows Users with the role 'Travel Team Member' to access the dashboard.
- add 'Travel Team Member' to included permissions to view the dashboard
- add 'Travel Team Member' to included permissions for the navigation
link to the dashboard.
- Checkout the **ch-travel-team-views-dashboard-162232273** branch
`git checkout ch-travel-team-views-dashboard-162232273`
- Start the [backend](https://github.com/andela/travel_tool_back/pull/188) of this project.
- Navigate to [travela](http://travela-local.andela.com:3000/) in …
> #162232273 Allow travel team members to view dashboard

- src/components/TravelCheckList/travelSubmission.scss
It enables users to use Grammarly while uploading checklist submissions and re-aligns the date and time locations.
- Time and date should be aligned more to the left
- Grammarly injection should be possible without distorting the text area field
- Clone this branch `git clone -b bg-fix-grammarly-misalignment-162261103 https://github.com/andela/travel_tool_front.git`
- Start server `make start`
- Navigate to travela in your browser and log in
- Create a request and change its status to `Approved`
- Click the dropdown-menu ellipsis
- Click `Travel Checklist`
- Ensure Grammarly is turned on
- Start typing in the text-area. It should not be misaligned or distorted. 
[162261103](https://www.pivotaltracker.com/story/show/162261103)
> #162261103 Fix text-area misalignment 

- src/components/AnalyticsReport/index.jsx
Update card label to correspond with content of card
- update label to read "Number of trips per department"
- checkout this branch - `git checkout bg-fix-card-label-162304867`
- run `yarn db:rollmigrate` on the backend directory and run `yarn start:dev`
- login to the app as a manager
- go to `http://localhost:3000/dashboard`
- scroll to the analytics cards.
- Card Label previously read as "Number of Trips/ Month"
- You must be logged in with a role of manager or higher to view dashboard page
[#162304867](https://www.pivotaltracker.com/story/show/162304867)
None
> #162304867 Modify label on Trips card

- src/components/AnalyticsReport/__tests__/AnalyticsReport.test.js
- src/components/AnalyticsReport/index.jsx
- src/components/AnalyticsReport/index.scss
- src/components/LeftSideBar/LeftSideNavItems/LeftSideNavItem/_leftSideNavItem.scss
- src/components/Pagination/AnalyticsPagination.jsx
- src/components/Pagination/__tests__/AnalyticsPagination.test.js
- src/components/Pagination/__tests__/__snapshots__/AnalyticsPagination.test.js.snap
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/TravelCalendar/__tests__/__snapshots__/TravelCalendar.test.js.snap
- src/components/TravelCalendarDetails/__tests__/__snapshots__/TravelCalendarDetails.test.js.snap
- src/components/TravelReadiness/__tests__/__snapshots__/travelReadiness.test.js.snap
- src/components/TravelReadiness/__tests__/travelReadiness.test.js
- src/components/TravelReadiness/index.jsx
- src/redux/__mocks__/mocks.js
- src/redux/middleware/__tests__/travelReadinessSaga.test.js
- src/redux/middleware/travelReadinessSaga.js
- src/redux/reducers/__tests__/readiness.test.js
- src/redux/reducers/readiness.js
Implement pagination on Travel Readiness Card
- Write functions to handle page change events
- Update css to match mockup
- Write tests for these functions
- Change directory - cd travel_tool_front
- Checkout to current branch - git checkout ft-travel-readiness-pagination-162168429`
- Start the server - make start
- Install dependencies on the frontend - yarn install
- Start the server - yarn start
- Navigate to localhost:3000 in a browser
- Assign yourself the manager role and Travel Admin role so as to be able to approve your request in the database and view the dashboard page
- Navigate to the requests page and make a new request selecting your location as the destination.
- Navigate to the approvals page …
> #162168429 Implement pagination on Travel Readiness Card

- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/TravelCalendar/index.jsx
- src/views/Documents/__tests__/index.test.js
- src/views/Documents/index.js
- by default disable save button on the rename document modal
- disable the next button on the calendar details from navigating to the next page when clicked
- The save button should be disabled by default unless the user changes the name of the document.
- When all the records have been fetched the button should be disabled and not clickable.
- Setting up the backend
- Clone the repo - `git clone https://github.com/andela/travel_tool_back.git`
- Enter into the project directory - `cd travel_tool_back`
- checkout the branch git checkout `develop`
- Install dependencies using `yarn install`
- Rollback and run database migrations with `yarn db:rollmigrate`
- start the backend server with `yarn run start:dev`
- Setting up the frontend
- Clone the repo - `git clone …
> #162310451 Fix bug on renaming a travel document.

- .codeclimate.yml
- .gitignore
- cypress/integration/component/Requests/create-request.spec.js
- cypress/integration/component/Requests/request.spec.js
- cypress/integration/component/logout.spec.js
- cypress/support/commands.js
- src/components/Forms/NewRequestForm/NewRequestForm.jsx
Adds end-to-end tests that ensure that users can create different request types
- Add tests for the request form validations
- Add tests for creating one-way, return and multi request
- Open the terminal  
- Create `cypress.env.json` file in the root directory and add your token following the format:
``{
"token": "your_token"
}``
- Run `yarn end2end` to run the test with browser mode
- When redirected to the browser, select `component/Requests/create-request.spec.js`
- The tests should run and pass
- To run test only in the console, run `yarn end2end:headless` 
- Ensure both the frontend and backend servers are running
[#161876890](https://www.pivotaltracker.com/story/show/161876890)
N/A
N/A
> #161876890 User can create different request types(End-to-end test)

- .gitignore
- cypress/integration/component/Requests/request.spec.js
- cypress/integration/component/Requests/view-request-details.spec.js
- cypress/integration/component/logout.spec.js
- cypress/support/commands.js
Adds end-to-end tests that ensure that users can view details of a request
- Create a request
- Add tests to ensure that the user can view the details of the request
- Open the terminal 
- Create `cypress.env.json` file in the root directory and add your token following the format:
``{
"token": "your_token"
}``
- Run `yarn end2end` to run the test with browser mode
- When redirected to the browser, select `component/Requests/view-request-details.spec.js`
- The tests should run and pass
- To run test only in the console, run `yarn end2end:headless` 
- Ensure both the frontend and backend servers are running
[#161877486](https://www.pivotaltracker.com/story/show/161877486)
N/A
N/A
> #161877486 User can view details of a request(End-to-end test)

- src/components/PieChartAnalytics/__tests__/PieChartAnalytics.test.js
- src/components/PieChartAnalytics/index.jsx
- src/views/Analytics/index.jsx
Use different colors to display separate charts
- represent each sector on the pie chart with separate shade
- use different base color for each chart on the analytics dashboard
- checkout this branch - `git checkout bg-fix-card-label-162304867`
- run `yarn db:rollmigrate` on the backend directory and run `yarn start:dev`
- login to the app as a manager
- go to `http://localhost:3000/dashboard`
None
[#162305445](https://www.pivotaltracker.com/story/show/162305445)
None
> #162305445 Fix colour scheme in dashboard pie charts

- src/components/Timeline/RoomsGeomWrapper/TripGeometry/TripDetails/TripDetails.scss
This PR fixed the issue with the positioning of the changeroom modal on the timeline.
- Ensure that the changeroom modal is fully visible for every approved request for the guesthouse.
- Ensure that none of the modal is hidden by any other elements on the page
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_front.git``` 
- Checkout to `bg-fix-changeroom-modal-position-162381911`
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_back.git``` 
- Checkout to `develop`
- Assign yourself the `Manager` role by changing your roleId to 50319 in the `UserRoles` table
- Make a return trip request using yourself as the manager to the destination used.
- Assign yourself the `Travel Administrator` role by changing …
> #162381911 Fix changeroom modal position

- src/components/Forms/NewRequestForm/FormFieldsets/SubmitArea.jsx
- src/components/Forms/NewRequestForm/NewRequestForm.jsx
This PR fixes the approvals bug on updating manager on the edit request form
- On editing the manager for an open request the manager should see the approval on his `Approvals` page
* Clone the repos: ``` https://github.com/andela/travel_tool_front ``` and ``` https://github.com/andela/travel_tool_back ```.
* cd into their respective directories ```travel_tool_front``` and ```travel_tool_back```.
* On the frontend and backend checkout `bg-fix-manager-bug-on-edit-162421358` branch.
* Start the backend by running the `$yarn run start:dev`
* Start the frontend by running `$yarn start`
* Login and create a new request.
* On the newly created request click on the ellipsis and edit it.
* Change the manager and update the request.
* The request should appear on the newly assigned managers …
> #162421358 Fix manager change on request approval bug

- cypress/fixtures/approvals/approval.json
- cypress/integration/component/Approvals/approval.spec.js
Adds end-to-end test for approvals page for the scenario when a manager has a pending approval
- Add end-to-end tests to confirm visibility of necessary items
- Add fixture to mock data when a manager has a pending approval
- Open the terminal  
- Run `yarn end2end` to run the test with browser mode
- When redirected to the browser, select `component/Approvals/approval.spec.js`
- The tests should run and pass
- To run test only in the console, run `yarn end2end:headless` 
- Ensure both the frontend and backend servers are running
[#162126795](https://www.pivotaltracker.com/story/show/162126795)
N/A
N/A
> #162126795 End to End tests for Manager can view right items on approvals page

- src/components/Forms/NewRequestForm/NewRequestForm.jsx
This PR ensures the app doesn't crash when you open the new request form.
- When you click on the id of a request on the verifications page and go to the requests page and create a new request.
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_front.git``` 
- Checkout to `bg-fx-request-form-crashing-162604565`
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_back.git``` 
- Checkout to `develop`
- Assign yourself the `Manager`, `Travel Admin` and `Requester` role by changing your roleId in the `UserRoles` table.
- Make `New Request` and assign yourself as the manager.
- Approve it and update the request with the relevant travel checklist items.
- Navigate to the `Requests` page and click the `New Request` …
> #162604565 Fix bug with new request form crashing app

- cypress/integration/component/UserRoles/assign-role.spec.js
- cypress/integration/component/UserRoles/user-role.spec.js
- cypress/support/commands.js
- add end to end test for user roles
- check if user roles page renders correctly
- Checkout to this branch `git checkout ch-e2e-user-roles-162375845`
- Run the command below on your terminal to rollback, migrate and seed e2e data to your database
`yarn db:rollback && yarn db:migrate && yarn db:seed:e2e`
- run `yarn start:dev`
- checkout this branch - `git checkout ch-e2e-user-roles-162375845`
- Open a new terminal
- Run `yarn end2end` to run the test with browser mode
- When redirected to the browser, select the following
- 'component/UserRoles/assign-role.spec.js'
- 'component/UserRoles/user-role.spec.js' …
> #162375845 Test to ensure that roles are enforced with Travela roles

- .gitignore
- cypress/integration/component/Requests/edit-request.spec.js
- Verify that only open requests can be edited and that the edit shows up on the requests table 
- Add end to end tests that verify:
- the edit request modal is displayed, pre-filled with the relevant request's information
- only open requests can be edited and that the edit shows up on the requests table
- errors are displayed and the submit button is disabled when the required fields are empty
- Checkout the **ch-e2e-edit-open-request-162122460** branch
`git checkout ch-e2e-edit-open-request-162122460`
`make start`
- Create a user …
> #162122460 E2E: User can only edit an open request 

- src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
fix inconsistent accommodation dropdown list
- make "arrival date" validation optional for one-way trips
- checkout this branch - `git checkout bg-fix-accomodation-dropdown-162698516`
- login to the app
- create a new travel request for a one-way trip and select `hotel booking` for accommodation.
- Edit the request and change `hotel booking` to an available room.
- Click the request to view the details and confirm that it has been updated
- Open the edit request modal once more. The available rooms option should be prepopulated with the last booking you selected
[#162698516](https://www.pivotaltracker.com/story/show/162698516)
None
None
> #162698516 Fix accommodation dropdown inconsistency for one way trips

- src/components/TravelCheckList/SubmissionsUtils.jsx
This PR changes ticket number to flight number in the trip planner modal
Currently, the field for entering Flight Number in the trip planner model is named `Ticket Number`
This PR changes the name of that field to `Flight Number`
- Checkout the **ch-change-ticket-number-to-flight-number-162711373** branch
`git checkout ch-change-ticket-number-to-flight-number-162711373`
- Start the server
- `yarn start` or `make start` *if you have docker*
- Under `Requests`, create a new request.
- Approve the new request
- Click on `Travel Checklist` in the …
> #162711373 change ticket number to flight number

- src/components/AnalyticsCard/index.scss
- src/components/AnalyticsReport/index.jsx
- src/components/TravelCalendar/index.jsx
- src/components/TravelReadiness/__tests__/travelReadiness.test.js
- src/components/TravelReadiness/index.jsx
Fixes card titles fonts, travel readiness pagination and message for no data on the dashboard page
- show Travel Readiness pagination only if data exists
- Set analytics card title fonts to match mockups
- display a consistent message on all cards when no data is available.
- clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
- checkout this branch - `git checkout bg-fix-dashboard-layout-162728852`
- clone the backend repo - `git clone https://github.com/andela/travel_tool_back.git`
- on the backend directory run `yarn db:rollmigrate` the run `yarn start:dev`
- login to the app on your browser
- assign yourself the `Travel Adminstrator` role using Postico
- navigate to the dashboard page
- ensure you have no `Travel Readiness` data.
- ensure …
> #162728852 Fix dashboard components

- src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
- src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
- src/components/Forms/ProfileForm/_tests_/ProfileForm.test.jsx
- src/components/Forms/ProfileForm/index.jsx
- src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
- src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
- src/helper/permissions/__tests__/permissions.test.js
- src/helper/permissions/index.js
- src/helper/roles.js
- src/hoc/Layout/__tests__/Layout.test.jsx
- src/hoc/Layout/__tests__/__snapshots__/Layout.test.jsx.snap
- src/hoc/Layout/index.jsx
- src/hoc/__tests__/__snapshots__/authHoc.test.js.snap
- src/hoc/authHoc.js
- src/routes/index.js
- src/views/Accommodation/index.jsx
- src/views/Approvals/index.jsx
- src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
- src/views/Checklist/index.jsx
- src/views/Dashboard/__tests__/.test.js
- src/views/Dashboard/__tests__/Dashboard.test.js
- src/views/Dashboard/index.jsx
- src/views/Role/index.jsx
- src/views/RoleDetails/index.js
- src/views/UserProfile/index.jsx
- src/views/Verifications/index.jsx
- Ensures the credentials for users are checked before the page content loads
- Protect the routes based on the user's roles
- Ensure the page content loads after the user's role has been verified
- Checkout the **bg-fix-user-access-162726866** branch
`git checkout bg-fix-user-access-162726866`
- Log in as a requester
- …
> #162726866 Ensure user role is checked before content loads

- src/components/Forms/NewRequestForm/FormFieldsets/TravelDetailsItem.jsx
- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/TravelDetailsItem.test.js
- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
- src/components/Forms/NewRequestForm/NewRequestForm.jsx
- src/components/Forms/NewRequestForm/NewRequestForm.scss
- src/components/RequestsModal/RequestModalHelper.js
- src/components/RequestsModal/TripDetails/index.jsx
- src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
- src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
- src/redux/reducers/__tests__/requests.test.js
- src/redux/reducers/requests.js
This PR fixes the bugs on the request page for multi-city requests.
* Make the `Not Required` accommodation option available.
* Make it the default placeholder for roundtrips.
* Ensure roundtrips where `Not Required` was selected displays it when it's viewed.
- Clone both repositories with ```git clone https://github.com/andela/travel_tool_front ``` and ```git clone https://github.com/andela/travel_tool_back ```
- CD into ```travel_tool_back ```  for the back-end and ```travel_tool_front ```  for the front-end
- Checkout to the branch ```bg-accommodation-availability-multicity-162711180``` for the back-end.
- Run ```yarn db:rollmigrate``` to update your database due to the changes that were made
- Start up the back-end ```yarn start:dev```.
- When you create a user with your front end. …
> #162711180 Fix accommodation option for Round Trips

- src/components/Table/index.jsx
This PR fixes the requests date created inconsistency
* Change the value passed to `updatedAt`.
- Clone the front end repository with ```git clone https://github.com/andela/travel_tool_front ``` 
- CD into ```travel_tool_front ``` 
- Checkout the **bg-fix-requests-date-created-inconsistency-162910388** branch
`git checkout bg-fix-requests-date-created-inconsistency-162910388`
- Install dependencies and start the server as stated in the ReadMe on this repository.
- Navigate to [travela …
> #162711180 Fix requests date created inconsistency

- src/components/CalendarRange/__tests__/__snapshots__/CalendarRange.test.js.snap
- src/components/DashboardHeader/__tests__/__snapshots__/index.test.js.snap
- src/components/Forms/FormsAPI/formValidator/index.js
- src/components/Forms/NewRequestForm/FormFieldsets/__tests__/__snapshots__/TravelDetails.test.js.snap
- src/components/Forms/ProfileForm/ProfileForm.scss
- src/components/Forms/ProfileForm/_tests_/ProfileForm.test.jsx
- src/components/Forms/ProfileForm/index.jsx
- src/components/RequestsModal/TripDetails/__tests__/__snapshots__/TripDetails.test.jsx.snap
- src/components/RequestsModal/__tests__/__snapshots__/RequestsModal.test.js.snap
- src/components/Timeline/RoomsGeomWrapper/BedGeomWrapper/__tests__/__snapshots__/BedGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/RoomGeomWrapper/__tests__/__snapshots__/RoomGeomWrapper.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/TripGeometry/__tests__/__snapshots__/TripGeometry.test.jsx.snap
- src/components/Timeline/RoomsGeomWrapper/__tests__/__snapshots__/RoomsGeomWrapper.test.jsx.snap
- src/components/Timeline/__tests__/__snapshots__/Timeline.test.jsx.snap
- src/redux/actionCreator/userProfileActions.js
- src/redux/middleware/UserProfileSaga.js
- src/redux/reducers/user.js
- src/views/CheckIn/__tests__/__snapshots__/CheckIn.test.js.snap
- src/views/UserProfile/__tests__/__snapshots__/UserProfile.test.js.snap
- src/views/UserProfile/index.jsx
- Fixes the inconsistencies on the profile page
Ensure the following issues are addressed
- When a user tries to type in their name, the user input is not captured as they type it unless you first select the department.
- When a user selects their gender as the first input, the styling becomes inconsistent (see attached screenshot)
- When a user successfully updates their profile, the success message is rendered as expected but the input dialogue does not update with the user's input hence it is rendered with empty fields unless the user reloads the page
- Checkout the **bg-profile-page-inconsistencies-162813288** branch
`git checkout …
> #162813288 Fix profile page inconsistencies
